Repository depromeet/Swimie-server, pull requests merged in 2024-07, with the labels that each got.

#10 feat: 공통 예외 및 성공 Response 구현
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/main/java/com/depromeet/domain/member/exception/MemberErrorCode.java
  src/main/java/com/depromeet/domain/member/exception/MemberException.java
  src/main/java/com/depromeet/domain/member/service/MemberServiceImpl.java
  src/main/java/com/depromeet/global/dto/response/ApiResponse.java
  src/main/java/com/depromeet/global/dto/type/ErrorType.java
  src/main/java/com/depromeet/global/dto/type/SuccessType.java
  src/main/java/com/depromeet/global/dto/type/common/CommonErrorType.java
  src/main/java/com/depromeet/global/dto/type/member/MemberErrorType.java
  src/main/java/com/depromeet/global/dto/type/member/MemberSuccessType.java
  src/main/java/com/depromeet/global/exception/BadRequestException.java
  src/main/java/com/depromeet/global/exception/BaseException.java
  src/main/java/com/depromeet/global/exception/ExceptionType.java
  src/main/java/com/depromeet/global/exception/ForbiddenException.java
  src/main/java/com/depromeet/global/exception/GlobalExceptionAdvice.java
  src/main/java/com/depromeet/global/exception/InternalServerException.java
  src/main/java/com/depromeet/global/exception/NotFoundException.java
  src/main/java/com/depromeet/global/exception/UnauthorizedException.java
  src/main/resources/application-local.yml
Labels: feature

#14 feat: Gradle Spotless 컨벤션 세팅
  build.gradle
  scripts/pre-commit
  src/main/java/com/depromeet/Application.java
  src/main/java/com/depromeet/domain/auth/controller/AuthController.java
  src/main/java/com/depromeet/domain/auth/dto/request/LoginDto.java
  src/main/java/com/depromeet/domain/auth/dto/response/JwtTokenResponseDto.java
  src/main/java/com/depromeet/domain/auth/service/AuthService.java
  src/main/java/com/depromeet/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/depromeet/domain/auth/service/JwtTokenService.java
  src/main/java/com/depromeet/domain/member/controller/MemberController.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/member/domain/MemberRole.java
  src/main/java/com/depromeet/domain/member/dto/request/MemberCreateDto.java
  src/main/java/com/depromeet/domain/member/dto/request/MemberUpdateDto.java
  src/main/java/com/depromeet/domain/member/dto/response/MemberFindOneResponseDto.java
  src/main/java/com/depromeet/domain/member/repository/MemberEntity.java
  src/main/java/com/depromeet/domain/member/repository/MemberJpaRepository.java
  src/main/java/com/depromeet/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/depromeet/domain/member/service/MemberServiceImpl.java
  src/main/java/com/depromeet/domain/member/service/port/MemberRepository.java
  src/main/java/com/depromeet/global/converter/AbstractCodedEnumConverter.java
  src/main/java/com/depromeet/global/converter/CodedEnum.java
  src/main/java/com/depromeet/global/dto/response/ApiResponse.java
  src/main/java/com/depromeet/global/dto/type/ErrorType.java
  src/main/java/com/depromeet/global/dto/type/SuccessType.java
  src/main/java/com/depromeet/global/dto/type/auth/AuthErrorType.java
  src/main/java/com/depromeet/global/dto/type/common/CommonErrorType.java
  src/main/java/com/depromeet/global/dto/type/member/MemberErrorType.java
  src/main/java/com/depromeet/global/dto/type/member/MemberSuccessType.java
  src/main/java/com/depromeet/global/exception/BadRequestException.java
  src/main/java/com/depromeet/global/exception/BaseException.java
  src/main/java/com/depromeet/global/exception/ForbiddenException.java
  src/main/java/com/depromeet/global/exception/GlobalExceptionAdvice.java
  src/main/java/com/depromeet/global/exception/InternalServerException.java
  src/main/java/com/depromeet/global/exception/NotFoundException.java
  src/main/java/com/depromeet/global/exception/UnauthorizedException.java
  src/main/java/com/depromeet/global/properties/ScanningPropertiesConfiguration.java
  src/main/java/com/depromeet/global/security/PrincipalDetails.java
  src/main/java/com/depromeet/global/security/SecurityConfig.java
  src/main/java/com/depromeet/global/security/constant/SecurityConstant.java
  src/main/java/com/depromeet/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/depromeet/global/security/jwt/util/AccessTokenDto.java
  src/main/java/com/depromeet/global/security/jwt/util/JwtProperties.java
  src/main/java/com/depromeet/global/security/jwt/util/JwtUtils.java
  src/main/java/com/depromeet/global/security/jwt/util/RefreshTokenDto.java
  src/main/java/com/depromeet/global/swagger/SwaggerConfig.java
  src/main/java/com/depromeet/global/swagger/SwaggerProperties.java
  src/test/java/com/depromeet/ApplicationTests.java
Labels: feature

#19 docs: 이슈 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/♾️-chore.md
  .github/ISSUE_TEMPLATE/🌟-feature.md
  .github/ISSUE_TEMPLATE/📜-docs.md
  .github/ISSUE_TEMPLATE/📝-test.md
  .github/ISSUE_TEMPLATE/📝test.md
  .github/ISSUE_TEMPLATE/🛠️-fix.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#24 fix: pre-commit 버그 수정 (#22)
  build.gradle
  gradlew
  module-presentation/src/test/java/com/depromeet/.gitkeep
Labels: 🚨🚨🚨🚨emergency, fix

#25 feat: 수영 기록(Memory, MemoryDetail, Stroke, Pool) 도메인 클래스 및 엔티티 구현
  module-domain/src/main/java/com/depromeet/memory/Memory.java
  module-domain/src/main/java/com/depromeet/memory/MemoryDetail.java
  module-domain/src/main/java/com/depromeet/memory/Stroke.java
  module-domain/src/main/java/com/depromeet/pool/Pool.java
  module-infrastructure/persistence-database/build.gradle
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryDetailEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/entity/PoolEntity.java
Labels: feature

#28 feat: 구글 소셜로그인 구현
  module-independent/src/main/java/com/depromeet/type/auth/AuthSuccessType.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponseDto.java
  module-presentation/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/java/com/depromeet/security/oauth/CustomOAuth2User.java
  module-presentation/src/main/java/com/depromeet/security/oauth/CustomOAuth2UserService.java
  module-presentation/src/main/java/com/depromeet/security/oauth/dto/GoogleResponse.java
  module-presentation/src/main/java/com/depromeet/security/oauth/dto/MemberDto.java
  module-presentation/src/main/java/com/depromeet/security/oauth/handler/OAuth2SuccessHandler.java
  module-presentation/src/main/resources/application-security.yml
Labels: feature, refactor

#31 feat: Jenkins CI/CD 구현
  scripts/Dockerfile-dev
  scripts/Dockerfile-prod
  scripts/Jenkinsfile
  scripts/Jenkinsfile-dev
Labels: feature

#36 feat: 이미지 업로드/수정/조회/삭제 기능 구현
  module-domain/src/main/java/com/depromeet/image/Image.java
  module-independent/src/main/java/com/depromeet/type/image/ImageErrorType.java
  module-independent/src/main/java/com/depromeet/type/image/ImageSuccessType.java
  module-independent/src/main/java/com/depromeet/util/ImageNameUtil.java
  module-infrastructure/persistence-database/build.gradle
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/entity/ImageEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepositoryImpl.java
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/config/AWSS3Config.java
  module-presentation/src/main/java/com/depromeet/config/AwsS3Properties.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/dto/request/ImageUpdateDto.java
  module-presentation/src/main/java/com/depromeet/image/dto/request/ImageUploadDto.java
  module-presentation/src/main/java/com/depromeet/image/dto/request/ImagesMemoryIdDto.java
  module-presentation/src/main/java/com/depromeet/image/dto/response/MemoryImagesDto.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageDeleteService.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageDeleteServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageGetService.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageGetServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateService.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/java/com/depromeet/security/oauth/handler/OAuth2FailureHandler.java
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application-security.yml
Labels: feature

#34 feat: 수영장 검색 API 구현
  .gitignore
  module-independent/src/main/java/com/depromeet/type/pool/PoolSuccessType.java
  module-infrastructure/persistence-database/build.gradle
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/QuerydslConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolInfoDto.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolResponseDto.java
  module-presentation/src/main/java/com/depromeet/pool/service/PoolService.java
  module-presentation/src/main/java/com/depromeet/pool/service/PoolServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/resources/application-local.yml
Labels: feature

#43 fix: s3 url 조회시 파일이 깨지는 문제 해결
  module-domain/src/main/java/com/depromeet/image/Image.java
  module-independent/src/main/java/com/depromeet/type/image/ImageErrorType.java
  module-independent/src/main/java/com/depromeet/type/image/ImageSuccessType.java
  module-independent/src/main/java/com/depromeet/util/ImageNameUtil.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/entity/ImageEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepositoryImpl.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/config/AWSS3Config.java
  module-presentation/src/main/java/com/depromeet/config/AwsS3Properties.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/dto/response/MemoryImagesDto.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageGetServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadServiceImpl.java
  module-presentation/src/main/resources/application-local.yml
Labels: fix

#46 feat: 기록 생성 시 Image의 FK를 채우는 기능 구현, 기록에 Pool 저장 구현
  module-domain/src/main/java/com/depromeet/image/Image.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/pool/PoolErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/entity/ImageEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/dto/request/ImagesMemoryIdDto.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/controller/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakePoolRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/MemoryServiceTest.java
Labels: feature

#47 feat: 영법 저장 구현
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/memory/controller/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeService.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeStrokeRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/StrokeServiceTest.java
Labels: feature

#56 feat: 카카오, 구글 소셜로그인 구현 - 프론트/백 책임 분배
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-presentation/src/main/java/com/depromeet/auth/controller/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/GoogleAccessTokenRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/GoogleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/KakaoAccessTokenRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/KakaoLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/AccountProfileResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/GoogleAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/KakaoAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/KakaoAccountProfileResponse.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthService.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthServiceImpl.java
  module-presentation/src/main/java/com/depromeet/auth/util/GoogleClient.java
  module-presentation/src/main/java/com/depromeet/auth/util/KakaoClient.java
  module-presentation/src/main/java/com/depromeet/config/RestTemplateConfig.java
  module-presentation/src/main/java/com/depromeet/member/service/MemberService.java
  module-presentation/src/main/java/com/depromeet/member/service/MemberServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/resources/application-security.yml
Labels: feature

#60 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/auth/controller/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/GoogleAccessTokenRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/GoogleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/KakaoAccessTokenRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/KakaoLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/AccountProfileResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/GoogleAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/KakaoAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/KakaoAccountProfileResponse.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthServiceImpl.java
  module-presentation/src/main/java/com/depromeet/auth/util/GoogleClient.java
  module-presentation/src/main/java/com/depromeet/auth/util/KakaoClient.java
  module-presentation/src/main/java/com/depromeet/member/service/MemberServiceImpl.java
Labels: deploy

#63 feat: 기록 상세 단일 조회 구현
  module-domain/src/main/java/com/depromeet/member/Member.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/entity/ImageEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/GoogleAccessTokenRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/GoogleAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/KakaoAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUploadServiceImpl.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSimpleResponse.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeService.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeStrokeRepository.java
Labels: feature

#64 fix: spotless 적용
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
Labels: 🚨🚨🚨🚨emergency, fix

#65 fix: spotless 적용
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeStrokeRepository.java
Labels: 🚨🚨🚨🚨emergency, fix

#68 fix: CORS 정책 수정 및 Swagger 추가
  module-presentation/src/main/java/com/depromeet/config/SwaggerConfig.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
Labels: chore, refactor, fix

#69 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/config/SwaggerConfig.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
Labels: deploy

#70 feat: timeline 최신순 무한스크롤 구현
  .gitignore
  module-domain/src/main/java/com/depromeet/memory/Memory.java
  module-independent/src/main/java/com/depromeet/dto/response/CustomSliceResponse.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepositoryImpl.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepositoryImpl.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/TestConfiguration.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/TestQueryDslConfig.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MemberFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/MemoryDetailFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/MemoryFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/StrokeFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/pool/MockPool.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-infrastructure/persistence-database/src/test/resources/application.yml
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/auth/dto/request/LoginDto.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthService.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthServiceImpl.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponseDto.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponseDto.java
  module-presentation/src/main/java/com/depromeet/memory/service/TimelineService.java
  module-presentation/src/main/java/com/depromeet/memory/service/TimelineServiceImpl.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemoryRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakePoolRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/StrokeServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/TimelineServiceTest.java
Labels: feature

#72 feat: 수영 기록 상세 수정 구현
  module-domain/src/main/java/com/depromeet/image/Image.java
  module-domain/src/main/java/com/depromeet/memory/Memory.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryDetailErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryDetailEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepositoryImpl.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepositoryImpl.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeService.java
  module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemoryDetailRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemoryRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeStrokeRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/MemoryServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/StrokeServiceTest.java
Labels: feature

#78 fix: image controller 오류 수정
  module-independent/src/main/java/com/depromeet/type/image/ImageSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageJpaRepository.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageApi.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
Labels: fix

#82 feat: 캘린더 조회 API 구현
  module-domain/src/main/java/com/depromeet/member/Member.java
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepositoryImpl.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSimpleResponse.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/DayResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponseDto.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponseDto.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/service/CalendarService.java
  module-presentation/src/main/java/com/depromeet/memory/service/CalendarServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryValidator.java
  module-presentation/src/main/java/com/depromeet/memory/service/TimelineServiceImpl.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemoryRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/MemoryServiceTest.java
Labels: chore, feature, refactor

#83 feat: JWT refresh token 구현
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtAccessTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/auth/service/AuthService.java
  module-presentation/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
  module-presentation/src/main/java/com/depromeet/security/constant/SecurityConstant.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtExceptionFilter.java
  module-presentation/src/main/java/com/depromeet/security/jwt/util/ErrorResponse.java
  module-presentation/src/main/java/com/depromeet/security/jwt/util/JwtUtils.java
  module-presentation/src/main/java/com/depromeet/security/jwt/util/RefreshTokenDto.java
  module-presentation/src/main/java/com/depromeet/security/oauth/handler/OAuth2SuccessHandler.java
Labels: feature

#87 feat: Sentry APM 및 에러 모니터링 도입
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/main/resources/application-prod.yml
Labels: feature

#93 feat: 목표 수정 및 조회 구현 배포
  module-domain/src/main/java/com/depromeet/member/Member.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepositoryImpl.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalApi.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/GoalUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/service/MemberService.java
  module-presentation/src/main/java/com/depromeet/member/service/MemberServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/filter/JwtAuthenticationFilter.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemberRepository.java
Labels: deploy, feature

#96 feat: Github Actions CI 스크립트 추가
  .github/workflows/CI.yml
  module-presentation/src/main/java/com/depromeet/member/api/GoalApi.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
Labels: chore

#97 deploy: 서버 배포
  .github/workflows/CI.yml
  module-presentation/src/main/java/com/depromeet/member/api/GoalApi.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
Labels: deploy

#100 test: MemoryController, PoolController, PoolService 테스트 코드 작성
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/memory/dto/request/TimelineRequestDto.java
  module-presentation/src/main/java/com/depromeet/pool/service/PoolServiceImpl.java
  module-presentation/src/test/java/com/depromeet/memory/config/ControllerTestConfig.java
  module-presentation/src/test/java/com/depromeet/memory/controller/MemoryControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/PoolControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/MemberFixture.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/PoolFixture.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakePoolRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/WithCustomMockMember.java
  module-presentation/src/test/java/com/depromeet/memory/mock/WithCustomMockMemberSecurityContextFactory.java
  module-presentation/src/test/java/com/depromeet/memory/service/PoolServiceTest.java
Labels: test

#105 refactor: Pool 도메인 헥사고날 아키텍처 전환
  module-domain/build.gradle
  module-domain/src/main/java/com/depromeet/memory/Memory.java
  module-domain/src/main/java/com/depromeet/pool/domain/FavoritePool.java
  module-domain/src/main/java/com/depromeet/pool/domain/Pool.java
  module-domain/src/main/java/com/depromeet/pool/domain/PoolSearch.java
  module-domain/src/main/java/com/depromeet/pool/port/in/command/FavoritePoolCommand.java
  module-domain/src/main/java/com/depromeet/pool/port/in/query/.gitkeep
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/FavoritePoolUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/InitialSearchUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/PoolSearchUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/SearchLogUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/out/persistence/PoolPersistencePort.java
  module-domain/src/main/java/com/depromeet/pool/service/PoolService.java
  module-domain/src/main/java/com/depromeet/pool/validator/PoolValidator.java
  module-infrastructure/persistence-database/build.gradle
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/entity/FavoritePoolEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/entity/PoolEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/entity/PoolSearchEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepositoryImpl.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/MemoryFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/pool/MockPool.java
  module-presentation/src/main/java/com/depromeet/config/SwaggerConfig.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolInfoResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolInitialResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolSearchInfoResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolSearchResponse.java
  module-presentation/src/main/java/com/depromeet/pool/facade/PoolFacade.java
  module-presentation/src/main/java/com/depromeet/pool/mapper/PoolMapper.java
  module-presentation/src/main/java/com/depromeet/pool/service/PoolService.java
  module-presentation/src/main/java/com/depromeet/pool/service/PoolServiceImpl.java
  module-presentation/src/main/java/com/depromeet/security/SecurityConfig.java
  module-presentation/src/test/java/com/depromeet/memory/controller/PoolControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/PoolFixture.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakePoolPersistencePort.java
  module-presentation/src/test/java/com/depromeet/memory/service/MemoryServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/PoolServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/TimelineServiceTest.java
Labels: refactor

#109 refactor: 수영장 검색 무한 스크롤 적용 및 초기 검색 결과 수정
  module-domain/src/main/java/com/depromeet/memory/vo/Timeline.java
  module-domain/src/main/java/com/depromeet/pool/domain/Pool.java
  module-domain/src/main/java/com/depromeet/pool/domain/vo/PoolSearchPage.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/PoolQueryUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/PoolSearchUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/out/persistence/PoolPersistencePort.java
  module-domain/src/main/java/com/depromeet/pool/service/PoolService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepositoryImpl.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolSearchJpaRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/memory/service/TimelineServiceImpl.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolInfoResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolInitialResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolSearchInfoResponse.java
  module-presentation/src/main/java/com/depromeet/pool/dto/response/PoolSearchResponse.java
  module-presentation/src/main/java/com/depromeet/pool/facade/PoolFacade.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeMemoryRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakePoolRepository.java
  module-presentation/src/test/java/com/depromeet/memory/service/MemoryServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/PoolServiceTest.java
  module-presentation/src/test/java/com/depromeet/memory/service/TimelineServiceTest.java
Labels: chore, refactor

#113 test: ImageService & ImageController 테스트 코드 작성
  module-presentation/src/test/java/com/depromeet/memory/controller/ImageControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/ImageFixture.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/MemoryDetailFixture.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/MemoryFixture.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/dto/ImageUploadResponseDtoFixture.java
  module-presentation/src/test/java/com/depromeet/memory/fixture/dto/MemoryImagesDtoFixture.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeImageRepository.java
  module-presentation/src/test/java/com/depromeet/memory/mock/FakeS3ImageManager.java
  module-presentation/src/test/java/com/depromeet/memory/service/ImageServiceTest.java
Labels: test

#118 refactor: 캘린더 조회 API 스펙 수정
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: refactor

#123 feat: laps 필드 0.5 단위 입력 가능하도록 데이터 타입 수정
  module-domain/src/main/java/com/depromeet/memory/domain/Stroke.java
  module-domain/src/main/java/com/depromeet/memory/port/in/command/CreateStrokeCommand.java
  module-domain/src/main/java/com/depromeet/memory/port/in/command/UpdateStrokeCommand.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/service/MemoryServiceTest.java
  module-domain/src/test/java/com/depromeet/service/StrokeServiceTest.java
  module-domain/src/test/java/com/depromeet/service/TimelineServiceTest.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/StrokeFixture.java
  module-presentation/src/main/java/com/depromeet/memory/annotation/HalfFloatCheck.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/validator/HalfFloatValidator.java
  module-presentation/src/test/java/com/depromeet/memory/controller/MemoryControllerTest.java
Labels: feature

#124 feat: 회원 이름 수정 API 구현
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/NameUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/NameUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/test/java/com/depromeet/config/ControllerTestConfig.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/ImageControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/MemoryControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/PoolControllerTest.java
Labels: feature

#129 fix: Auth Transactional read only 제거
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: 🚨🚨emergency🚨🚨, fix

#126 feat: 기록 상세 응답 형태 수정
  module-domain/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-domain/src/test/java/com/depromeet/service/MemoryServiceTest.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-presentation/src/main/java/com/depromeet/image/dto/response/ImageSimpleResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
Labels: refactor

#131 deploy: yml 설정 수정
  module-presentation/src/main/resources/application-prod.yml
Labels: deploy

#132 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/NameUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/main/java/com/depromeet/memory/domain/Stroke.java
  module-domain/src/main/java/com/depromeet/memory/port/in/command/CreateStrokeCommand.java
  module-domain/src/main/java/com/depromeet/memory/port/in/command/UpdateStrokeCommand.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-domain/src/test/java/com/depromeet/service/MemoryServiceTest.java
  module-domain/src/test/java/com/depromeet/service/StrokeServiceTest.java
  module-domain/src/test/java/com/depromeet/service/TimelineServiceTest.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/StrokeEntity.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/memory/StrokeFixture.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/image/dto/response/ImageSimpleResponse.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/NameUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/java/com/depromeet/memory/annotation/HalfFloatCheck.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/validator/HalfFloatValidator.java
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/config/ControllerTestConfig.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/ImageControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/MemoryControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/controller/PoolControllerTest.java
Labels: deploy
