Repository depromeet/Swimie-server, pull requests merged in 2024-10, with the labels that each got.

#440 fix: 100일이 지난 팔로잉 소식 삭제 배치의 ItemReader 가 제대로 동작하지 않는 문제 해결
  module-batch/src/main/java/com/depromeet/job/followinglog/reader/FollowingLogItemReader.java
  module-domain/src/main/java/com/depromeet/report/service/ReportService.java
  module-domain/src/main/java/com/depromeet/withdrawal/service/WithdrawalReasonService.java
Labels: bug

#442 hotfix: 수영 시간 계산 시 초 단위로 계산
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryReadUpdateResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
Labels: bug, 🚨🚨emergency🚨🚨, fix

#443 deploy: 배포
  module-batch/src/main/java/com/depromeet/job/followinglog/reader/FollowingLogItemReader.java
  module-domain/src/main/java/com/depromeet/report/service/ReportService.java
  module-domain/src/main/java/com/depromeet/withdrawal/service/WithdrawalReasonService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/DataSourceConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/JpaAuditingConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/JpaConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/RoutingDataSource.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followinglog/repository/FollowingMemoryLogRepository.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryReadUpdateResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/resources/application-prod-db.yml
  module-presentation/src/main/resources/application.yml
Labels: deploy

#448 fix: 응원 삭제 버그 수정
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
Labels: fix

#449 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
Labels: deploy

#446 feat: Naver Clova Studio API 도입 및 예시 API 생성
  module-domain/src/main/java/com/depromeet/ai/port/in/CreateInputTextCommand.java
  module-domain/src/main/java/com/depromeet/ai/port/in/usecase/AIUseCase.java
  module-domain/src/main/java/com/depromeet/ai/port/out/AIPort.java
  module-domain/src/main/java/com/depromeet/ai/service/AIService.java
  module-independent/src/main/java/com/depromeet/constant/ClovaStudioChatCompletionPrompt.java
  module-independent/src/main/java/com/depromeet/dto/ai/ChatCompletionsMessage.java
  module-independent/src/main/java/com/depromeet/dto/ai/ChatCompletionsRequest.java
  module-independent/src/main/java/com/depromeet/dto/ai/SummaryRequest.java
  module-independent/src/main/java/com/depromeet/type/ai/AIErrorType.java
  module-independent/src/main/java/com/depromeet/type/ai/AISuccessType.java
  module-infrastructure/ai/build.gradle
  module-infrastructure/ai/src/main/java/com/depromeet/ai/manage/ClovaStudioManager.java
  module-infrastructure/ai/src/main/java/com/depromeet/config/ClovaStudioProperties.java
  module-infrastructure/ai/src/main/java/com/depromeet/config/ScanningPropertiesConfig.java
  module-infrastructure/ai/src/main/resources/application-ai.yml
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/ai/api/AIApi.java
  module-presentation/src/main/java/com/depromeet/ai/api/AIController.java
  module-presentation/src/main/java/com/depromeet/ai/dto/request/SummaryTextRequest.java
  module-presentation/src/main/java/com/depromeet/ai/facade/AIFacade.java
  module-presentation/src/main/resources/application.yml
  settings.gradle
Labels: feature

#452 deploy: 서버 배포
  gradlew.bat
  module-domain/src/main/java/com/depromeet/greeting/domain/Greeting.java
  module-domain/src/main/java/com/depromeet/greeting/port/in/CreateInputTextCommand.java
  module-domain/src/main/java/com/depromeet/greeting/port/in/usecase/GreetingUseCase.java
  module-domain/src/main/java/com/depromeet/greeting/port/out/AIPort.java
  module-domain/src/main/java/com/depromeet/greeting/port/out/GreetingCachePort.java
  module-domain/src/main/java/com/depromeet/greeting/service/GreetingService.java
  module-independent/src/main/java/com/depromeet/constant/ClovaStudioChatCompletionPrompt.java
  module-independent/src/main/java/com/depromeet/dto/ai/ChatCompletionsMessage.java
  module-independent/src/main/java/com/depromeet/dto/ai/ChatCompletionsRequest.java
  module-independent/src/main/java/com/depromeet/dto/ai/SummaryRequest.java
  module-independent/src/main/java/com/depromeet/type/greeting/GreetingErrorType.java
  module-independent/src/main/java/com/depromeet/type/greeting/GreetingSuccessType.java
  module-infrastructure/module-ai/build.gradle
  module-infrastructure/module-ai/src/main/java/com/depromeet/config/ClovaStudioProperties.java
  module-infrastructure/module-ai/src/main/java/com/depromeet/config/ScanningPropertiesConfig.java
  module-infrastructure/module-ai/src/main/java/com/depromeet/greeting/manage/ClovaStudioManager.java
  module-infrastructure/module-ai/src/main/resources/application-ai.yml
  module-infrastructure/module-cache/build.gradle
  module-infrastructure/module-cache/src/main/java/com/depromeet/service/GreetingCacheService.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/config/RedisConfig.java
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/greeting/api/GreetingApi.java
  module-presentation/src/main/java/com/depromeet/greeting/api/GreetingController.java
  module-presentation/src/main/java/com/depromeet/greeting/dto/request/SummaryTextRequest.java
  module-presentation/src/main/java/com/depromeet/greeting/dto/response/GreetingResponse.java
  module-presentation/src/main/java/com/depromeet/greeting/facade/GreetingFacade.java
  module-presentation/src/main/resources/application.yml
  settings.gradle
Labels: deploy
