Repository depromeet/Swimie-server, pull requests merged in 2024-08, with the labels that each got.

#135 feat: PENDING 이미지 일괄 삭제 배치 서비스 구현
  module-batch/build.gradle
  module-batch/src/main/java/com/depromeet/BatchApplication.java
  module-batch/src/main/java/com/depromeet/config/BatchConfig.java
  module-batch/src/main/java/com/depromeet/config/ScanningPropertiesConfig.java
  module-batch/src/main/java/com/depromeet/job/image/InvalidImageDeleteJobConfig.java
  module-batch/src/main/java/com/depromeet/job/image/listener/ImageDeleteJobExecutionListener.java
  module-batch/src/main/java/com/depromeet/job/image/processor/ImageItemProcessor.java
  module-batch/src/main/java/com/depromeet/job/image/reader/ImageItemReader.java
  module-batch/src/main/java/com/depromeet/job/image/writer/ImageItemWriter.java
  module-batch/src/main/resources/application-batch.yml
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-infrastructure/object-storage/src/main/java/com/depromeet/manage/BatchS3ImageManager.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/test/java/com/depromeet/memory/api/MemoryControllerTest.java
  scripts/Dockerfile-image
  scripts/batch/Jenkinsfile-image
  scripts/shell/batch-image.sh
  scripts/shell/deploy.sh
  scripts/shell/local-batch-image.sh
  settings.gradle
Labels: feature, refactor

#136 deploy: 서버 배포
  module-batch/build.gradle
  module-batch/src/main/java/com/depromeet/BatchApplication.java
  module-batch/src/main/java/com/depromeet/config/BatchConfig.java
  module-batch/src/main/java/com/depromeet/config/ScanningPropertiesConfig.java
  module-batch/src/main/java/com/depromeet/job/image/InvalidImageDeleteJobConfig.java
  module-batch/src/main/java/com/depromeet/job/image/listener/ImageDeleteJobExecutionListener.java
  module-batch/src/main/java/com/depromeet/job/image/processor/ImageItemProcessor.java
  module-batch/src/main/java/com/depromeet/job/image/reader/ImageItemReader.java
  module-batch/src/main/java/com/depromeet/job/image/writer/ImageItemWriter.java
  module-batch/src/main/resources/application-batch.yml
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/image/service/ImageUpdateService.java
  module-domain/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-domain/src/test/java/com/depromeet/fixture/ClockFixture.java
  module-domain/src/test/java/com/depromeet/fixture/ImageFixture.java
  module-domain/src/test/java/com/depromeet/service/ImageServiceTest.java
  module-independent/src/main/java/com/depromeet/clock/ClockConfig.java
  module-independent/src/main/java/com/depromeet/util/ImageNameUtil.java
  module-infrastructure/object-storage/src/main/java/com/depromeet/manage/BatchS3ImageManager.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/test/java/com/depromeet/config/mock/WithCustomMockMember.java
  module-presentation/src/test/java/com/depromeet/config/mock/WithCustomMockMemberSecurityContextFactory.java
  module-presentation/src/test/java/com/depromeet/image/api/ImageControllerTest.java
  module-presentation/src/test/java/com/depromeet/image/fixture/MemberFixture.java
  module-presentation/src/test/java/com/depromeet/image/fixture/dto/ImageUploadResponseDtoFixture.java
  module-presentation/src/test/java/com/depromeet/image/fixture/dto/MemoryImagesDtoFixture.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/api/MemoryControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/api/PoolControllerTest.java
  scripts/Dockerfile-image
  scripts/batch/Jenkinsfile-image
  scripts/shell/batch-image.sh
  scripts/shell/deploy.sh
  scripts/shell/local-batch-image.sh
  settings.gradle
Labels: deploy

#141 refactor: 수영장 즐겨찾기 API 스펙 변경 및 Logback 설정
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-independent/src/main/java/com/depromeet/type/pool/PoolSuccessType.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/console-appender.xml
  module-presentation/src/main/resources/file-error-appender.xml
  module-presentation/src/main/resources/file-info-appender.xml
  module-presentation/src/main/resources/logback-spring.xml
  module-presentation/src/test/java/com/depromeet/pool/api/PoolControllerTest.java
Labels: feature, refactor

#142 deploy: 서버 배포
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-independent/src/main/java/com/depromeet/type/pool/PoolSuccessType.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/console-appender.xml
  module-presentation/src/main/resources/file-error-appender.xml
  module-presentation/src/main/resources/file-info-appender.xml
  module-presentation/src/main/resources/logback-spring.xml
  module-presentation/src/test/java/com/depromeet/pool/api/PoolControllerTest.java
Labels: deploy

#145 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryCreateResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolApi.java
Labels: deploy

#146 fix: 소셜로그인이 개발 환경, 배포 환경 모두에서 가능하도록 수정
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/GooglePort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/KakaoPort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-infrastructure/security/src/main/java/com/depromeet/util/KakaoClient.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/resources/application-security.yml
Labels: fix

#148 fix: TimelineResponse 불필요한 필드 제거 및 isAchieved 필드 추가
  module-domain/src/test/java/com/depromeet/service/TimelineServiceTest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
Labels: fix

#151 fix: 소셜로그인 origin 변경
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
Labels: fix

#152 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
Labels: deploy

#156 refactor: 수영 기록 API 스펙 수정
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryCreateResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  scripts/batch/Jenkinsfile-image
Labels: refactor

#157 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-domain/src/test/java/com/depromeet/fixture/MemoryDetailFixture.java
  module-domain/src/test/java/com/depromeet/fixture/MemoryFixture.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-domain/src/test/java/com/depromeet/service/ImageServiceTest.java
  module-domain/src/test/java/com/depromeet/service/TimelineServiceTest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryCreateResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/test/java/com/depromeet/memory/api/MemoryControllerTest.java
  scripts/batch/Jenkinsfile-image
Labels: deploy

#161 refactor: 캘린더 조회 및 타임라인 조회 API 스펙 변경
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSimpleResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineSliceResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: refactor

#159 fix: TimelineResponse 필드 추가/변경/제거
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-infrastructure/security/src/main/java/com/depromeet/SecurityConfig.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: fix

#164 refactor: 수영 기록 조회 API 스펙 변경
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
Labels: refactor

#166 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
Labels: deploy

#169 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/validator/HalfFloatValidator.java
  module-presentation/src/test/java/com/depromeet/image/api/ImageControllerTest.java
Labels: deploy

#170 refactor: 수영 기록 단건 조회 API 수정 및 AOP Custom Logger 구현
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/config/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/config/Logging.java
  module-presentation/src/main/java/com/depromeet/config/RequestLog.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/resources/logback-spring.xml
  scripts/Jenkinsfile
Labels: feature, refactor, fix

#171 deploy: 서버 배포
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/config/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/config/Logging.java
  module-presentation/src/main/java/com/depromeet/config/RequestLog.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/resources/logback-spring.xml
  scripts/Jenkinsfile
Labels: deploy

#178 fix: image content-type 이미지 확장자에 따라 변경
  module-domain/src/main/java/com/depromeet/image/port/out/s3/S3ManagePort.java
  module-domain/src/main/java/com/depromeet/image/service/ImageUpdateService.java
  module-domain/src/main/java/com/depromeet/image/service/ImageUploadService.java
  module-domain/src/test/java/com/depromeet/mock/FakeS3ImageManager.java
  module-domain/src/test/java/com/depromeet/service/ImageServiceTest.java
  module-independent/src/main/java/com/depromeet/constant/ImageTypeConstant.java
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-independent/src/main/java/com/depromeet/type/image/ImageErrorType.java
  module-independent/src/main/java/com/depromeet/util/ImageNameUtil.java
  module-infrastructure/object-storage/src/main/java/com/depromeet/manage/S3ImageManager.java
Labels: fix

#180 feat: 로그아웃 구현
  module-domain/src/main/java/com/depromeet/auth/port/out/persistence/RefreshRedisPersistencePort.java
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/port/in/command/SocialMemberCommand.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/mock/FakeRefreshRedisRepository.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-redis/build.gradle
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/.gitkeep
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/config/RedisConfig.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/repository/RefreshRedisRepository.java
  module-infrastructure/security/build.gradle
  module-infrastructure/security/src/main/java/com/depromeet/SecurityConfig.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2User.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/MemberDto.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/handler/CustomLogoutSuccessHandler.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/handler/OAuth2SuccessHandler.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/config/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/member/mapper/MemberMapper.java
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
Labels: feature

#183 fix: 수영기록 기록 시 laps 0으로 입력하고 meter를 0이상으로 입력하는 경우 조회 시 laps와 meter 전부가 0으로 조회 되는 이슈 해결
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
Labels: fix

#184 feat: 계정 탈퇴 및 소셜계정 연결 끊기 구현
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/GooglePort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/KakaoPort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/persistence/SocialRedisPersistencePort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/repository/SocialRedisRepository.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/GoogleAccessTokenResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/KakaoRevokeResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/KakaoTokenInfoResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-infrastructure/security/src/main/java/com/depromeet/util/KakaoClient.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: feature

#186 feat: 로그인 성공 시 이름 반환 및 성별 수정 구현
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/MemberGender.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/NameUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-independent/src/main/java/com/depromeet/annotation/Enum.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-independent/src/main/java/com/depromeet/validator/EnumValidator.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/GenderUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberGenderResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
Labels: feature

#188 deploy: 서버 배포, 데이터베이스 초기화
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/GooglePort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/KakaoPort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/persistence/RefreshRedisPersistencePort.java
  module-domain/src/main/java/com/depromeet/auth/port/out/persistence/SocialRedisPersistencePort.java
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/MemberGender.java
  module-domain/src/main/java/com/depromeet/member/port/in/command/SocialMemberCommand.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/NameUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/mock/FakeRefreshRedisRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-independent/src/main/java/com/depromeet/annotation/Enum.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthSuccessType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-independent/src/main/java/com/depromeet/validator/EnumValidator.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-redis/build.gradle
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/.gitkeep
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/config/RedisConfig.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/repository/RefreshRedisRepository.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/repository/SocialRedisRepository.java
  module-infrastructure/security/build.gradle
  module-infrastructure/security/src/main/java/com/depromeet/SecurityConfig.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2User.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/MemberDto.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/GoogleAccessTokenResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/KakaoRevokeResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/KakaoTokenInfoResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/handler/CustomLogoutSuccessHandler.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/handler/OAuth2SuccessHandler.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-infrastructure/security/src/main/java/com/depromeet/util/KakaoClient.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/config/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/GenderUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberGenderResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/java/com/depromeet/member/mapper/MemberMapper.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
Labels: deploy

#189 deploy: 사용자 정의 Bridge 네트워크 적용
  module-presentation/src/main/resources/application-prod.yml
  scripts/shell/deploy.sh
Labels: deploy

#191 deploy: 서버 배포
  scripts/shell/deploy.sh
Labels: deploy

#192 fix: redis config 추가
  module-presentation/src/main/resources/application-prod.yml
Labels: bug, deploy

#193 deploy: 서버 배포
  module-presentation/src/main/resources/application-prod.yml
Labels: deploy

#195 fix: name 컬럼 nickname 으로 변경
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/fixture/MemberFixture.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-domain/src/test/java/com/depromeet/service/MemoryServiceTest.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryJpaRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MockMember.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2User.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/MemberDto.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/NicknameUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberFindOneResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberGenderResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/image/fixture/MemberFixture.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/api/MemoryControllerTest.java
Labels: bug, fix

#197 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/fixture/MemberFixture.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/service/MemberServiceTest.java
  module-domain/src/test/java/com/depromeet/service/MemoryServiceTest.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryJpaRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MockMember.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2User.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/CustomOAuth2UserService.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/MemberDto.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/NicknameUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberFindOneResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberGenderResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/CalendarResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/image/fixture/MemberFixture.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
  module-presentation/src/test/java/com/depromeet/memory/api/MemoryControllerTest.java
Labels: deploy

#205 feat: 애플 로그인 구현
  .gitignore
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/ApplePort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-infrastructure/security/build.gradle
  module-infrastructure/security/src/main/java/com/depromeet/SecurityConfig.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleJwk.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleJwkSet.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleTokenResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/util/AppleClient.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/main/resources/application-security.yml
Labels: feature

#207 feat: 자신의 기록인지 확인할 수 있는 필드 추가
  module-domain/src/main/java/com/depromeet/memory/service/MemoryValidator.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: feature

#209 chore: 로그 관리, 환경 변수 runtime 주입
  .gitignore
  module-infrastructure/security/src/main/java/com/depromeet/util/AppleClient.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/resources/application-security.yml
  scripts/Jenkinsfile
  scripts/shell/deploy.sh
Labels: chore

#210 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/ApplePort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryValidator.java
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/basetime/BaseTimeEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/JpaConfig.java
  module-infrastructure/security/build.gradle
  module-infrastructure/security/src/main/java/com/depromeet/SecurityConfig.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleJwk.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleJwkSet.java
  module-infrastructure/security/src/main/java/com/depromeet/oauth/dto/response/AppleTokenResponse.java
  module-infrastructure/security/src/main/java/com/depromeet/util/AppleClient.java
  module-infrastructure/security/src/main/java/com/depromeet/util/GoogleClient.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/common/GlobalExceptionAdvice.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/main/resources/application-security.yml
  scripts/Jenkinsfile
  scripts/shell/deploy.sh
Labels: deploy

#211 fix: scp 디렉토리 수정
  scripts/Jenkinsfile
Labels: bug

#212 deploy: 서버 배포
  scripts/Jenkinsfile
Labels: deploy

#214 feat: 팔로워/팔로잉 기능 + member검색 + member 도메인에 profileImageUrl, introduction 추가
  module-domain/src/main/java/com/depromeet/friend/domain/Friend.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/FollowSlice.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Follower.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Following.java
  module-domain/src/main/java/com/depromeet/friend/port/in/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchPage.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowSuccessType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberSuccessType.java
  module-infrastructure/object-storage/src/main/java/com/depromeet/manage/S3ImageManager.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/entity/FriendEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MemberFixture.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MockMember.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/friend/repository/FriendRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/image/repository/ImageRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/request/FollowRequest.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowerFollowingCountResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowerResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/friend/mapper/FollowMapper.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberInfoResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSearchResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/java/com/depromeet/member/mapper/MemberMapper.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
  module-presentation/src/test/java/com/depromeet/member/controller/MemberControllerTest.java
Labels: feature

#218 feat: 응원 생성, 조회, 삭제 API 구현
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/main/java/com/depromeet/reaction/domain/Reaction.java
  module-domain/src/main/java/com/depromeet/reaction/domain/ReactionPage.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/command/CreateReactionCommand.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/CreateReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/DeleteReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/reaction/ReactionErrorType.java
  module-independent/src/main/java/com/depromeet/type/reaction/ReactionSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/entity/ReactionEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionApi.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/request/ReactionCreateRequest.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/MemoryReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/PagingReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/ReactionDetailResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
  module-presentation/src/main/java/com/depromeet/reaction/mapper/ReactionMapper.java
Labels: feature, refactor

#227 feat: 로그인 성공 응답에 최초 로그인 여부 표시
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: feature

#229 feat: 이전, 다음 기록 조회 구현
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: feature

#234 deploy: 서버 배포
  README.md
  scripts/Jenkinsfile
Labels: deploy

#240 hotfix: 타임라인 정렬 오류 수정 및 N+1 문제 개선 (#239)
  module-domain/src/main/java/com/depromeet/memory/service/TimelineService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
Labels: bug, 🚨🚨emergency🚨🚨

#249 feat: 응원 생성 여부 검증 API 구현
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-independent/src/main/java/com/depromeet/type/reaction/ReactionSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/reaction/annotation/SingleEmojiCheck.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionApi.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/request/ReactionCreateRequest.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/ValidateReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
  module-presentation/src/main/java/com/depromeet/reaction/validator/SingleEmojiValidator.java
  module-presentation/src/main/resources/static/favicon.ico
Labels: feature, refactor

#255 fix: http method가 delete인 경우 응답값 204 NoContent -> 200 으로 변경
  module-independent/src/main/java/com/depromeet/type/image/ImageSuccessType.java
  module-independent/src/main/java/com/depromeet/type/reaction/ReactionSuccessType.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageApi.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionApi.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/test/java/com/depromeet/image/api/ImageControllerTest.java
Labels: fix

#257 feat: 알림 API 구현
  module-domain/src/main/java/com/depromeet/followingLog/service/FollowingMemoryLogService.java
  module-domain/src/main/java/com/depromeet/notification/domain/FollowLog.java
  module-domain/src/main/java/com/depromeet/notification/domain/FollowType.java
  module-domain/src/main/java/com/depromeet/notification/domain/ReactionLog.java
  module-domain/src/main/java/com/depromeet/notification/event/FollowLogEvent.java
  module-domain/src/main/java/com/depromeet/notification/event/ReactionLogEvent.java
  module-domain/src/main/java/com/depromeet/notification/port/in/command/UpdateReadFollowLogCommand.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-independent/src/main/java/com/depromeet/type/notification/NotificationErrorType.java
  module-independent/src/main/java/com/depromeet/type/notification/NotificationSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/FollowLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/PersistenceFollowType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/ReactionLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/entity/ReactionEntity.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageApi.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationController.java
  module-presentation/src/main/java/com/depromeet/notification/dto/request/UpdateReadNotificationRequest.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/BaseNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FriendNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/NotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/ReactionNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/UnreadNotificationCountResponse.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
  module-presentation/src/main/java/com/depromeet/notification/mapper/NotificationMapper.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionApi.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
Labels: chore, feature, refactor

#259 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/followingLog/service/FollowingMemoryLogService.java
  module-domain/src/main/java/com/depromeet/notification/domain/FollowLog.java
  module-domain/src/main/java/com/depromeet/notification/domain/FollowType.java
  module-domain/src/main/java/com/depromeet/notification/domain/ReactionLog.java
  module-domain/src/main/java/com/depromeet/notification/event/FollowLogEvent.java
  module-domain/src/main/java/com/depromeet/notification/event/ReactionLogEvent.java
  module-domain/src/main/java/com/depromeet/notification/port/in/command/UpdateReadFollowLogCommand.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-independent/src/main/java/com/depromeet/type/notification/NotificationErrorType.java
  module-independent/src/main/java/com/depromeet/type/notification/NotificationSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/FollowLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/PersistenceFollowType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/ReactionLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/entity/ReactionEntity.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageApi.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalApi.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationController.java
  module-presentation/src/main/java/com/depromeet/notification/dto/request/UpdateReadNotificationRequest.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/BaseNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FriendNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/NotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/ReactionNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/UnreadNotificationCountResponse.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
  module-presentation/src/main/java/com/depromeet/notification/mapper/NotificationMapper.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionApi.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
Labels: deploy

#261 fix: followingMemoryLog에서 member_id 제거
  module-domain/src/main/java/com/depromeet/followingLog/domain/FollowingMemoryLog.java
  module-domain/src/main/java/com/depromeet/followingLog/port/in/command/CreateFollowingMemoryCommand.java
  module-domain/src/main/java/com/depromeet/followingLog/service/FollowingMemoryLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/entity/FollowingMemoryLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/repository/FollowingMemoryLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/followingLog/repository/FollowingMemoryLogRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/followingLog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: fix

#263 feat: 동일 API 동시 요청 제한 디바운스 구현
  module-independent/src/main/java/com/depromeet/type/common/CommonErrorType.java
  module-presentation/src/main/java/com/depromeet/common/DuplicateRequestAspect.java
Labels: feature

#266 feat: 탈퇴 사유 등록 API 개발 및 구글 스프레드시트 연동
  .gitignore
  module-domain/src/main/java/com/depromeet/withdrawal/domain/ReasonType.java
  module-domain/src/main/java/com/depromeet/withdrawal/port/in/command/CreateWithdrawalReasonCommand.java
  module-domain/src/main/java/com/depromeet/withdrawal/port/in/usecase/CreateWithdrawalReasonUseCase.java
  module-domain/src/main/java/com/depromeet/withdrawal/port/out/persistence/WithdrawalReasonPort.java
  module-domain/src/main/java/com/depromeet/withdrawal/service/WithdrawalReasonService.java
  module-independent/src/main/java/com/depromeet/type/withdrawal/WithdrawalReasonErrorType.java
  module-independent/src/main/java/com/depromeet/type/withdrawal/WithdrawalReasonSuccessType.java
  module-infrastructure/google-spreadsheet/build.gradle
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/config/ScanningPropertiesConfig.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/config/SpreadSheetProperties.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/spreadsheet/GoogleSheetManager.java
  module-infrastructure/google-spreadsheet/src/main/resources/application-spreadsheet.yml
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonApi.java
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonController.java
  module-presentation/src/main/java/com/depromeet/withdrawal/dto/request/WithdrawalReasonCreateRequest.java
  module-presentation/src/main/java/com/depromeet/withdrawal/facade/WithdrawalReasonFacade.java
  module-presentation/src/main/java/com/depromeet/withdrawal/mapper/WithdrawalReasonMapper.java
  module-presentation/src/main/resources/application.yml
  scripts/Jenkinsfile
  settings.gradle
Labels: feature

#267 fix: 회원 탈퇴 시 삭제될 데이터 추가 구현
  module-domain/src/main/java/com/depromeet/followingLog/port/in/FollowingMemoryLogUseCase.java
  module-domain/src/main/java/com/depromeet/followingLog/port/out/persistence/FollowingMemoryLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/followingLog/service/FollowingMemoryLogService.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/DeleteMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/DeleteFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/DeleteReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/FavoritePoolUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/in/usecase/SearchLogUseCase.java
  module-domain/src/main/java/com/depromeet/pool/port/out/persistence/PoolPersistencePort.java
  module-domain/src/main/java/com/depromeet/pool/service/PoolService.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-domain/src/test/java/com/depromeet/mock/FakePoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followingLog/repository/FollowingMemoryLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/pool/repository/PoolRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#269 fix: 회원 정보 수정 시 필드 Blank 체크 추가, 기본 프로필 이미지 기능 추가
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
Labels: fix

#273 hotfix: jenkins 명령어 수정 - not a directory 오류 수정
  scripts/Jenkinsfile
Labels: bug, fix

#274 deploy: 서버 배포
  scripts/Jenkinsfile
Labels: deploy

#277 deploy: 서버 배포
  scripts/Jenkinsfile
Labels: deploy

#279 deploy: 서버 배포
  scripts/Jenkinsfile
  scripts/shell/deploy.sh
Labels: deploy

#283 fix: 입력 값 검증 방식 변경
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/MemberUpdateRequest.java
Labels: fix

#284 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/MemberUpdateRequest.java
Labels: deploy

#287 refactor: 알림 조회 API 스펙 변경 및 로그 수집 방식 변경
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FriendNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/ReactionNotificationResponse.java
Labels: refactor

#291 fix: 알림 조회 시 응원 content null로 나오는 문제 해결
  module-presentation/src/main/java/com/depromeet/notification/dto/response/ReactionNotificationResponse.java
Labels: fix

#292 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/ReactionNotificationResponse.java
  scripts/Jenkinsfile
Labels: deploy

#294 fix: follow log 삭제 시 where 절 조건 수정
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
Labels: bug, 🚨🚨emergency🚨🚨, fix

#298 fix: stroke 가 저장되어 있지 않는 memory 대상으로 팔로잉 소식 조회 시 나타나는 NPE 오류 해결
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
Labels: bug, fix

#296 feat: 여러 회원에 대한 팔로우 여부 확인 기능 추가
  module-domain/src/main/java/com/depromeet/friend/domain/vo/FollowCheck.java
  module-domain/src/main/java/com/depromeet/friend/port/in/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/request/FollowCheckListRequest.java
  module-presentation/src/main/java/com/depromeet/friend/dto/request/FollowCheckResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/IsFollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
Labels: feature

#299 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/auth/service/JwtTokenService.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/FollowCheck.java
  module-domain/src/main/java/com/depromeet/friend/port/in/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/request/FollowCheckListRequest.java
  module-presentation/src/main/java/com/depromeet/friend/dto/request/FollowCheckResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/IsFollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
Labels: deploy

#301 feat: 기본 프로필 랜덤 설정 구현
  module-domain/src/main/java/com/depromeet/member/port/in/command/SocialMemberCommand.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-presentation/src/main/java/com/depromeet/auth/dto/response/JwtTokenResponse.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/member/mapper/MemberMapper.java
Labels: feature

#304 fix: Random 객체 경합 문제 해결
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#306 fix: 숫자 입력값(meter, laps, kcal...) 0이하로 입력이 되는 이슈 해결
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/GoalUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeUpdateRequest.java
Labels: fix

#308 feat: 기본 프로필 이미지인 경우 cloud front 도메인 제거 응답
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Follower.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Following.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchInfo.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberDetailResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberProfileResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSearchResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FriendNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/MemoryReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/PagingReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/ReactionDetailResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
Labels: feature

#309 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Follower.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Following.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchInfo.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/dto/request/GoalUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberDetailResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberProfileResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSearchResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/StrokeUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FriendNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/MemoryReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/PagingReactionResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/dto/response/ReactionDetailResponse.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
Labels: deploy

#311 fix: 팔로잉 여부 확인 응답 필드명 변경
  module-presentation/src/main/java/com/depromeet/friend/dto/response/IsFollowingResponse.java
Labels: fix

#314 fix: 회원 탈퇴 시 log 삭제 누락 수정
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/DeleteReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#316 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/DeleteReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowerResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/IsFollowingResponse.java
Labels: deploy

#317 fix: Reaction log 삭제 시 조건절 오류 수정
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/DeleteReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: bug, 🚨🚨emergency🚨🚨, fix

#318 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/DeleteReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#320 fix: 팔로잉 소식 응답값 필드명 변경(memberProfileUrl -> profileImageUrl)
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
Labels: fix

#321 deploy: 서버 배포를 시작합니다
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
Labels: deploy

#324 feat: 애플 로그인 요청 객체 수정
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/ApplePort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/auth/vo/apple/AppleAccountCommand.java
  module-infrastructure/security/src/main/java/com/depromeet/util/AppleClient.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleAccountInfo.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleNameInfo.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/auth/mapper/AppleMapper.java
Labels: feature

#325 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/auth/port/in/usecase/SocialUseCase.java
  module-domain/src/main/java/com/depromeet/auth/port/out/ApplePort.java
  module-domain/src/main/java/com/depromeet/auth/service/SocialService.java
  module-domain/src/main/java/com/depromeet/auth/vo/apple/AppleAccountCommand.java
  module-infrastructure/security/src/main/java/com/depromeet/util/AppleClient.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleAccountInfo.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleLoginRequest.java
  module-presentation/src/main/java/com/depromeet/auth/dto/request/AppleNameInfo.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/auth/mapper/AppleMapper.java
Labels: deploy

#331 fix: 도메인 이름 수정
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: bug, 🚨🚨emergency🚨🚨, fix

#332 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#334 fix: 알림 조회 API 버그 수정
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
Labels: fix

#337 fix: 팔로잉 여부 조회 시 자신의 계정을 조회하는 경우 에러 제거
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
Labels: fix

#339 fix: 구글 스프레드 시트 json 읽어오는 클래스 FileInputStream으로 변경
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/spreadsheet/GoogleSheetManager.java
Labels: fix

#340 refactor: 디바운싱 로직 변경
  module-presentation/src/main/java/com/depromeet/common/DuplicateRequestAspect.java
Labels: refactor

#341 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/GetFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/spreadsheet/GoogleSheetManager.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-presentation/src/main/java/com/depromeet/common/DuplicateRequestAspect.java
  module-presentation/src/main/java/com/depromeet/notification/dto/response/FollowNotificationResponse.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
Labels: deploy

#343 refactor: 팔로잉 여부 조회 API 스펙 변경
  module-domain/src/main/java/com/depromeet/friend/port/in/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingStateResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
Labels: refactor, rename

#346 refactor: 수영 기록 수정 API undefined 핸들링
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryDetailPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryDetailRepository.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryDetailEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: refactor

#347 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryDetailPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryDetailRepository.java
  module-domain/src/test/java/com/depromeet/mock/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryDetailEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryDetailResponse.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: deploy

#348 hotfix: 수영 기록 시 nullable 필드 핸들링
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: 🚨🚨emergency🚨🚨, fix

#349 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryCreateRequest.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: deploy
