Repository depromeet/Swimie-server, pull requests merged in 2024-09, with the labels that each got.

#359 refactor: ReactionLog 복합 인덱스를 이용한 API 성능 개선
  module-domain/src/main/java/com/depromeet/notification/domain/ReactionLog.java
  module-domain/src/main/java/com/depromeet/notification/event/ReactionLogEvent.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/entity/ReactionLogEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-presentation/src/main/java/com/depromeet/reaction/facade/ReactionFacade.java
Labels: refactor

#361 fix: 성별 선택 안 함 추가
  module-domain/src/main/java/com/depromeet/member/domain/MemberGender.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
Labels: fix

#364 fix: 회원 탈퇴 시 Memory Detail 이 없는 경우 에러 수정
  module-domain/src/main/java/com/depromeet/memory/domain/vo/MemoryAndDetailId.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/followinglog/repository/FollowingMemoryLogRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/image/repository/ImageRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#365 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/domain/vo/MemoryAndDetailId.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryDetailRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/followinglog/repository/FollowingMemoryLogRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/image/repository/ImageRepositoryTest.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#366 refactor: timeline api
  module-domain/src/main/java/com/depromeet/image/domain/vo/MemoryImageUrlVo.java
  module-domain/src/main/java/com/depromeet/image/port/in/ImageGetUseCase.java
  module-domain/src/main/java/com/depromeet/image/port/out/persistence/ImagePersistencePort.java
  module-domain/src/main/java/com/depromeet/image/service/ImageGetService.java
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/TimelineUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/TimelineService.java
  module-domain/src/main/java/com/depromeet/reaction/domain/vo/ReactionCount.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-domain/src/test/java/com/depromeet/mock/image/FakeImageRepository.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-domain/src/test/java/com/depromeet/service/memory/TimelineServiceTest.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: refactor

#368 feat: 수영장 검색 API 관련 성능 체크 및 MATCH-AGAINST 함수 추가
  module-infrastructure/persistence-database/src/main/java/com/depromeet/util/CustomFunction.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/util/MatchFunctionContributor.java
  module-infrastructure/persistence-database/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: feature

#374 feat: Blacklist 도메인 및 엔티티 구현
  module-domain/src/main/java/com/depromeet/blacklist/domain/Blacklist.java
  module-domain/src/main/java/com/depromeet/blacklist/port/.gitkeep
  module-domain/src/main/java/com/depromeet/blacklist/service/.gitkeep
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/entity/BlacklistEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/.gitkeep
Labels: feature

#372 feat: 기록 삭제 구현
  module-domain/src/main/java/com/depromeet/followinglog/port/in/FollowingMemoryLogUseCase.java
  module-domain/src/main/java/com/depromeet/followinglog/port/out/persistence/FollowingMemoryLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/followinglog/service/FollowingMemoryLogService.java
  module-domain/src/main/java/com/depromeet/image/port/in/ImageUpdateUseCase.java
  module-domain/src/main/java/com/depromeet/image/port/out/persistence/ImagePersistencePort.java
  module-domain/src/main/java/com/depromeet/image/service/ImageUpdateService.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/DeleteMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/StrokeUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/StrokePersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/main/java/com/depromeet/memory/service/StrokeService.java
  module-domain/src/main/java/com/depromeet/reaction/port/in/usecase/GetReactionUseCase.java
  module-domain/src/main/java/com/depromeet/reaction/port/out/persistence/ReactionPersistencePort.java
  module-domain/src/main/java/com/depromeet/reaction/service/ReactionService.java
  module-domain/src/test/java/com/depromeet/mock/image/FakeImageRepository.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeStrokeRepository.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followinglog/repository/FollowingMemoryLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/StrokeRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: feature

#382 feat: 유저 차단하기 API 구현
  module-domain/src/main/java/com/depromeet/blacklist/port/.gitkeep
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistCommandUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/.gitkeep
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistErrorType.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistSuccessType.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/.gitkeep
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistApi.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/request/BlackMemberRequest.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
Labels: feature

#384 feat: 사용자 차단 해제 API 구현
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistCommandUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistApi.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
Labels: feature

#388 feat: 신고 구글 스프레드시트 연동 구현
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberIdAndNickname.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/main/java/com/depromeet/memory/domain/vo/MemoryIdAndDiaryAndMember.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/main/java/com/depromeet/report/domain/ReportReasonCode.java
  module-domain/src/main/java/com/depromeet/report/port/in/command/CreateReportCommand.java
  module-domain/src/main/java/com/depromeet/report/port/in/usecase/CreateReportUseCase.java
  module-domain/src/main/java/com/depromeet/report/port/out/persistence/ReportPersistencePort.java
  module-domain/src/main/java/com/depromeet/report/service/ReportService.java
  module-domain/src/test/java/com/depromeet/mock/member/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/report/ReportErrorType.java
  module-independent/src/main/java/com/depromeet/type/report/ReportSuccessType.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/config/SpreadSheetProperties.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/spreadsheet/GoogleSheetManager.java
  module-infrastructure/google-spreadsheet/src/main/resources/application-spreadsheet.yml
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportApi.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportController.java
  module-presentation/src/main/java/com/depromeet/report/dto/request/ReportRequest.java
  module-presentation/src/main/java/com/depromeet/report/facade/ReportFacade.java
  module-presentation/src/main/java/com/depromeet/report/mapper/ReportMapper.java
Labels: feature

#386 feat: 팔로워/팔로잉 리스트에서 차단한 사람/본인을 차단한 사람 안 보이게 필터링
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/FollowSlice.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/test/java/com/depromeet/mock/friend/FakeFriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/friend/repository/FriendRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
Labels: feature

#390 feat: 차단한 사용자 조회 API 구현
  module-domain/src/main/java/com/depromeet/blacklist/domain/vo/BlacklistPage.java
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistErrorType.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistSuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistApi.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/response/BlackMemberDetailResponse.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/response/BlackMemberResponse.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
Labels: feature

#391 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/blacklist/domain/vo/BlacklistPage.java
  module-domain/src/main/java/com/depromeet/blacklist/port/.gitkeep
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistCommandUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/.gitkeep
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-domain/src/main/java/com/depromeet/friend/domain/vo/FollowSlice.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/domain/Member.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberIdAndNickname.java
  module-domain/src/main/java/com/depromeet/member/port/in/usecase/MemberUseCase.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/main/java/com/depromeet/memory/domain/vo/MemoryIdAndDiaryAndMember.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/main/java/com/depromeet/report/domain/ReportReasonCode.java
  module-domain/src/main/java/com/depromeet/report/port/in/command/CreateReportCommand.java
  module-domain/src/main/java/com/depromeet/report/port/in/usecase/CreateReportUseCase.java
  module-domain/src/main/java/com/depromeet/report/port/out/persistence/ReportPersistencePort.java
  module-domain/src/main/java/com/depromeet/report/service/ReportService.java
  module-domain/src/test/java/com/depromeet/mock/friend/FakeFriendRepository.java
  module-domain/src/test/java/com/depromeet/mock/member/FakeMemberRepository.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistErrorType.java
  module-independent/src/main/java/com/depromeet/type/blacklist/BlacklistSuccessType.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-independent/src/main/java/com/depromeet/type/report/ReportErrorType.java
  module-independent/src/main/java/com/depromeet/type/report/ReportSuccessType.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/config/SpreadSheetProperties.java
  module-infrastructure/google-spreadsheet/src/main/java/com/depromeet/spreadsheet/GoogleSheetManager.java
  module-infrastructure/google-spreadsheet/src/main/resources/application-spreadsheet.yml
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/.gitkeep
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistJpaRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/friend/repository/FriendRepositoryTest.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistApi.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/request/BlackMemberRequest.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/response/BlackMemberDetailResponse.java
  module-presentation/src/main/java/com/depromeet/blacklist/dto/response/BlackMemberResponse.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportApi.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportController.java
  module-presentation/src/main/java/com/depromeet/report/dto/request/ReportRequest.java
  module-presentation/src/main/java/com/depromeet/report/facade/ReportFacade.java
  module-presentation/src/main/java/com/depromeet/report/mapper/ReportMapper.java
Labels: deploy

#392 feat: 유저 검색 시 차단한 사람/본인을 차단한 사람 안 보이게 하는 기능 추가
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchInfo.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchPage.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/test/java/com/depromeet/mock/member/FakeMemberRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberInfoResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSearchResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/test/java/com/depromeet/friend/api/FollowControllerTest.java
Labels: feature

#395 feat: 마이페이지 차단 구현
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-domain/src/main/java/com/depromeet/report/domain/ReportReasonCode.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/resources/application-prod.yml
Labels: feature

#394 feat: 유저 차단 시 팔로워/팔로잉 리스트에서 삭제 및 차단한 유저/본인을 차단한 유저를 팔로우 할 때 예외 처리
  module-domain/src/main/java/com/depromeet/friend/port/in/command/DeleteFollowCommand.java
  module-domain/src/main/java/com/depromeet/friend/port/in/usecase/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/test/java/com/depromeet/mock/friend/FakeFriendRepository.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
Labels: feature

#396 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-domain/src/main/java/com/depromeet/friend/port/in/command/DeleteFollowCommand.java
  module-domain/src/main/java/com/depromeet/friend/port/in/usecase/FollowUseCase.java
  module-domain/src/main/java/com/depromeet/friend/port/out/persistence/FriendPersistencePort.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchInfo.java
  module-domain/src/main/java/com/depromeet/member/domain/vo/MemberSearchPage.java
  module-domain/src/main/java/com/depromeet/member/port/out/persistence/MemberPersistencePort.java
  module-domain/src/main/java/com/depromeet/member/service/MemberService.java
  module-domain/src/main/java/com/depromeet/report/domain/ReportReasonCode.java
  module-domain/src/test/java/com/depromeet/mock/friend/FakeFriendRepository.java
  module-domain/src/test/java/com/depromeet/mock/member/FakeMemberRepository.java
  module-independent/src/main/java/com/depromeet/type/friend/FollowErrorType.java
  module-independent/src/main/java/com/depromeet/type/member/MemberErrorType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/member/repository/MemberRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowApi.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberInfoResponse.java
  module-presentation/src/main/java/com/depromeet/member/dto/response/MemberSearchResponse.java
  module-presentation/src/main/java/com/depromeet/member/facade/MemberFacade.java
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/test/java/com/depromeet/friend/api/FollowControllerTest.java
Labels: deploy

#399 fix: 없는 member_id로 차단 시도 시 예외 처리
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
Labels: fix

#401 fix: 회원 탈퇴 시 차단 데이터 삭제
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#402 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/blacklist/port/in/usecase/BlacklistQueryUseCase.java
  module-domain/src/main/java/com/depromeet/blacklist/port/out/persistence/BlacklistPersistencePort.java
  module-domain/src/main/java/com/depromeet/blacklist/service/BlacklistService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/blacklist/repository/BlacklistRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/blacklist/facade/BlacklistFacade.java
Labels: deploy

#404 refactor: 팔로워/팔로우 리스트 리팩토링 및 타임라인 리팩토링
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Follower.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/friend/repository/FriendRepositoryTest.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/config/RedisCacheConfig.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogSliceResponse.java
  module-presentation/src/main/java/com/depromeet/followinglog/facade/FollowingLogFacade.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowerResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingStateResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingSummaryResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineSliceResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: refactor

#407 fix: 회원 탈퇴 시 MemoryDetailId NPE 수정
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#408 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/friend/domain/vo/Follower.java
  module-domain/src/main/java/com/depromeet/friend/service/FollowService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/friend/repository/FriendRepository.java
  module-infrastructure/persistence-database/src/test/java/com/depromeet/friend/repository/FriendRepositoryTest.java
  module-infrastructure/persistence-redis/src/main/java/com/depromeet/redis/config/RedisCacheConfig.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/followinglog/dto/response/FollowingLogSliceResponse.java
  module-presentation/src/main/java/com/depromeet/followinglog/facade/FollowingLogFacade.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowSliceResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowerResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingStateResponse.java
  module-presentation/src/main/java/com/depromeet/friend/dto/response/FollowingSummaryResponse.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/StrokeResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/TimelineSliceResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/memory/mapper/MemoryMapper.java
Labels: deploy

#409 fix: 회원 탈퇴 시 MemoryDetailId NPE 수정 및 애플 로그인 오류 코드 반환
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#410 deploy: 서버 배포
  module-independent/src/main/java/com/depromeet/type/auth/AuthErrorType.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#411 fix: ImmutableCollections 문제 해결
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#412 deploy: 서버 배포
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#414 fix: 애플로그인 인증서버로부터 계정 정보를 받지 못할 때 에러 핸들링
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: fix

#415 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/auth/facade/AuthFacade.java
Labels: deploy

#417 feat: 기록 단일 조회 응답에 N번째 기록 추가
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportApi.java
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonApi.java
Labels: feature

#418 deploy: 서버 배포
  module-presentation/src/main/java/com/depromeet/memory/dto/response/MemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportApi.java
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonApi.java
Labels: deploy

#419 refactor: 로그 추적을 용이하게 하기 위한 MDC 적용
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/config/log/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/config/log/Logging.java
  module-presentation/src/main/java/com/depromeet/config/log/RequestLog.java
  module-presentation/src/main/java/com/depromeet/config/log/mdc/MDCFilter.java
  module-presentation/src/main/java/com/depromeet/followinglog/api/FollowingLogController.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationController.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportController.java
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonController.java
  module-presentation/src/main/resources/logback-spring.xml
  scripts/Dockerfile-dev
  scripts/Dockerfile-image
  scripts/Dockerfile-prod
Labels: refactor

#423 refactor: 알림 일괄 읽음 처리
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationController.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
  module-presentation/src/main/resources/application-prod.yml
  scripts/Dockerfile-prod
  scripts/Jenkinsfile
Labels: chore, refactor

#425 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateFollowLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/in/usecase/UpdateReactionLogUseCase.java
  module-domain/src/main/java/com/depromeet/notification/port/out/FollowLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/port/out/ReactionLogPersistencePort.java
  module-domain/src/main/java/com/depromeet/notification/service/FollowLogService.java
  module-domain/src/main/java/com/depromeet/notification/service/ReactionLogService.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/FollowLogRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/notification/repository/ReactionLogRepository.java
  module-presentation/src/main/java/com/depromeet/auth/api/AuthController.java
  module-presentation/src/main/java/com/depromeet/blacklist/api/BlacklistController.java
  module-presentation/src/main/java/com/depromeet/config/log/LoggerConfig.java
  module-presentation/src/main/java/com/depromeet/config/log/Logging.java
  module-presentation/src/main/java/com/depromeet/config/log/RequestLog.java
  module-presentation/src/main/java/com/depromeet/config/log/mdc/MDCFilter.java
  module-presentation/src/main/java/com/depromeet/followinglog/api/FollowingLogController.java
  module-presentation/src/main/java/com/depromeet/friend/api/FollowController.java
  module-presentation/src/main/java/com/depromeet/image/api/ImageController.java
  module-presentation/src/main/java/com/depromeet/member/api/GoalController.java
  module-presentation/src/main/java/com/depromeet/member/api/MemberController.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationApi.java
  module-presentation/src/main/java/com/depromeet/notification/api/NotificationController.java
  module-presentation/src/main/java/com/depromeet/notification/facade/NotificationFacade.java
  module-presentation/src/main/java/com/depromeet/pool/api/PoolController.java
  module-presentation/src/main/java/com/depromeet/reaction/api/ReactionController.java
  module-presentation/src/main/java/com/depromeet/report/api/ReportController.java
  module-presentation/src/main/java/com/depromeet/withdrawal/api/WithdrawalReasonController.java
  module-presentation/src/main/resources/application-prod.yml
  module-presentation/src/main/resources/logback-spring.xml
  scripts/Dockerfile-dev
  scripts/Dockerfile-image
  scripts/Dockerfile-prod
  scripts/Jenkinsfile
Labels: deploy

#426 hotfix: 타임라인 조회 시 응원 개수가 제대로 카운트 되지 않는 이슈 해결
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
Labels: bug

#429 refactor: MDC 유저 실제 IP로 보이도록 수정
  module-presentation/src/main/java/com/depromeet/config/log/mdc/MDCFilter.java
Labels: refactor

#430 deploy: 서버 배포를 시작합니다
  module-infrastructure/persistence-database/src/main/java/com/depromeet/reaction/repository/ReactionRepository.java
  module-presentation/src/main/java/com/depromeet/config/log/mdc/MDCFilter.java
Labels: deploy

#433 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/src/main/java/com/depromeet/config/log/mdc/MDCFilter.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
Labels: refactor

#435 feat: 직전 수영 기록 정보 조회 구현, Flyway 적용
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/LastMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/LastPoolResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/db/migration/V1__init.sql
  module-presentation/src/main/resources/db/migration/V2__add_column_to_memory.sql
Labels: feature

#436 deploy: 서버 배포
  module-domain/src/main/java/com/depromeet/memory/domain/Memory.java
  module-domain/src/main/java/com/depromeet/memory/port/in/usecase/GetMemoryUseCase.java
  module-domain/src/main/java/com/depromeet/memory/port/out/persistence/MemoryPersistencePort.java
  module-domain/src/main/java/com/depromeet/memory/service/MemoryService.java
  module-domain/src/test/java/com/depromeet/mock/memory/FakeMemoryRepository.java
  module-independent/src/main/java/com/depromeet/type/memory/MemoryErrorType.java
  module-independent/src/main/java/com/depromeet/type/memory/MemorySuccessType.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/repository/MemoryRepository.java
  module-presentation/build.gradle
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
  module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/LastMemoryResponse.java
  module-presentation/src/main/java/com/depromeet/memory/dto/response/LastPoolResponse.java
  module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
  module-presentation/src/main/resources/application-db.yml
  module-presentation/src/main/resources/db/migration/V1__init.sql
  module-presentation/src/main/resources/db/migration/V2__add_column_to_memory.sql
Labels: deploy

#420 feat: MySQL Replication 수행
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/DataSourceConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/JpaAuditingConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/JpaConfig.java
  module-infrastructure/persistence-database/src/main/java/com/depromeet/config/RoutingDataSource.java
  module-presentation/src/main/resources/application-prod-db.yml
  module-presentation/src/main/resources/application.yml
Labels: feature, refactor

#437 refactor: 팔로잉 소식 조회 쿼리 성능 개선
  module-infrastructure/persistence-database/src/main/java/com/depromeet/followinglog/repository/FollowingMemoryLogRepository.java
  module-presentation/src/main/java/com/depromeet/friend/facade/FollowFacade.java
Labels: refactor
